version: '3.1'

services:
  drupal:
    image: drupal:9-latest
    ports:
      - 80
    volumes:
      - ./:/opt/drupal/
    restart: always

  mysql:
    image: mysql:8-debian
    environment:
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - mysql:/var/lib/mysql
    restart: always

volumes:
  mysql:
