version: '3.1'

services:
  drupal:
    build: .
    image: drupal:9-apache
    container_name: drupal
    ports:
      - 8888:80
    restart: always
    volumes:
      - ./:/opt/drupal/

  mysql:
    image: mariadb:10
    container_name: mysql
    environment:
      MARIADB_ROOT_PASSWORD: drupal
      MARIADB_DATABASE: drupal
      MARIADB_USER: drupal
      MARIADB_PASSWORD: drupal
    ports:
      - 3306:3306
    volumes:
      - ./.docker-compose/data/:/var/lib/mysql
